---
title: Доска объявлений
output:
  html_document:
    toc: false
    toc_float:
      collapsed: false
    highlight: haddock
    include:
      after_body: _footer.html
    css: my_styles.css
---

**Коллеги!**

Поскольку на курс записалось очень много слушателей, то для успешной работы нам придется использовать, в том числе, и онлайн технологии. На нашей первой встрече **17.04.2024 (10:00)** мы определимся, кто будет работать в очном режиме (компьютерный класс ЭБЦ), а кто будет размещен в соседних кабинетах и будет на связи через систему Яндекс-Телемост. Для использования этой системы ничего устанавливать не требуется. Необходимо будет подключиться к Интернету (через вайфай в ЭБЦ, пароль для доступа вам дадут, или через смартфон, используя его как точку доступа) и пройти по [этой ссылке](https://telemost.yandex.ru/j/62606309069166). 


**Важно!**

Для успешной работы вне аудитории нам нужно будет общаться. Для этого крайне рекомендуется установить Telegram не только на смартфон, но и на [компьютер](https://desktop.telegram.org/). Далее необходимо присоединиться к ТГ-каналу [**"R для исследовательских работ"**](https://t.me/+GX06d2X2DAEzMzgy).

**Занятия 23.04.2022**

Коллеги! Все, кто работал в прошлый раз в компьютерном классе (115 кабинет) 23 апреля (начало в 10.00) приходите вновь туда же.

**Для работы в онлайн присоединяемся по вот этой [ссылке](https://telemost.yandex.ru/j/13894335034654)**




