---
title: Материалы для занятий
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
    highlight: haddock
    include:
      after_body: _footer.html
    css: my_styles.css
---

# **Первые действия**

Идеальная ситуация - это когда вы будете работать со своим собственным компьютером (ноутбук или стационарная машина). Это понадобится для выполнения домашних заданий, да и вообще, так удобнее. Если у вас нет своего собственного компьютера, то вы сможете использовать мощности компьютерного класса ЭБЦ "Крестовский остров". 

**До начала занятий** вам понадобится установить две программы: **R** и **RStudio**. Ниже даны инструкции как это сделать.


- [Установка R и RStudio на компьютеры под OC Windows](Intro_to_R_first_steps.html)
- [Установка R и RStudio на компьютеры под OC Linux (тестировано на Ubuntu 22.04.3)](https://drive.google.com/file/d/1AjBSoWZ3DmXt-7Rv88jfCbQNm1M1aEmM/view?usp=sharing)


# **Пособия, которые помогут разобраться в материалах курса**

- [Визуализация даных с помощью ggplot2](https://drive.google.com/file/d/1lGfc0yjIYHBYst5HYuNBiSuQ9I-kXoZ5/view?usp=sharing) 

- [Статистическая обработка данных на языке R](https://drive.google.com/file/d/1GVYorXdbCyx5ypy1cZ_rIhBf4dR_xR_2/view?usp=drive_link)

**Дополнительно:** Некоторые пособия (на английском языке) вы найдете на страничке "Полезности" нашего сайта.

<br>
<br>


# Занятие 1. **Основы языка статистического программирования R**

- [Скрипт для работы в аудитории](first_steps.R)
- [Данные для работы  аудитории](data/hydrology_2022.xls)

<br>

- [Домашнее задание Вариант 1](01_intro_to_R_HW1_Var_1.html)
- [Домашнее задание Вариант 2](01_intro_to_R_HW1_Var_2.html)
- [Данные для выполненеия ДЗ(catsM.xlsx)](data/catsM.xlsx)

<br>

- [Презентация для самостоятельного знакомства с R](01_intro_to_r.html)


# Видео для первого занятия

- [Запись второй части занятия](https://drive.google.com/file/d/13mg4cG_TaXQ2W-XWjPVAAug9EE3e92rL/view?usp=drive_link)

Внимание! Приведенные ниже видео являются собственностью СПбГУ. Огромная просьба НЕ распространять эти материалы. Они открыты только для вашего персонального пользования.

- [Знакомство с R. **Видео 1**](https://drive.google.com/file/d/1exV9KycXjCC3Ej2c111dVlIlaR_ZUGiy/view?usp=drive_link)
- [Знакомство с R. **Видео 2**](https://drive.google.com/file/d/1iXmOD0tnHJri2EBqVprciUez32Zgcj1Q/view?usp=drive_link)
- [Знакомство с R. **Видео 3**](https://drive.google.com/file/d/1trXj35-vBh8gLjdGkh_vKyFxZQ5opLmS/view?usp=drive_link)
- [Знакомство с R. **Видео 4**](https://drive.google.com/file/d/1lCRxzhJ5BS2TWIbMyvR5WL92uzSP0vAW/view?usp=drive_link)
- [Знакомство с R. **Видео 5**](https://drive.google.com/file/d/1XJKxIpa7Rt_ao3oOy3wHhzX4Wb0ZgfsE/view?usp=drive_link)






